Store/Store/Models/CatalogItemModel.cs
namespace Store.Models
{
	public class CatalogItemModel
	{
		public int Id { get; set; }

		public string Title { get; set; }

		public string Description { get; set; }
	}
}

Store/Store/Models/CatalogModel.cs
using System.Collections.Generic;

namespace Store.Models
{
	public class CatalogModel
	{
		public string Title { get; set; }

		public List<CatalogItemModel> Categories { get; set; }

		public List<ProductDetailsModel> Products { get; set; }

		public ProductFilterModel ProductFilter { get; set; }
	}
}

Store/Store/Models/ErrorViewModel.cs
using System;

namespace Store.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Store/Store/Models/ProductDetailsModel.cs
namespace Store.Models
{
	public class ProductDetailsModel
	{
		public int Id { get; set; }

		public string Title { get; set; }

		public string Description { get; set; }

		public int CategoryId { get; set; }
	}
}

Store/Store/Models/ProductFilterModel.cs
namespace Store.Models
{
	public class ProductFilterModel
	{
	}
}

Store/Store/Models/ProductModel.cs
using System.Collections.Generic;

namespace Store.Models
{
	public class ProductModel
	{
		public string Title { get; set; }

		public ProductDetailsModel ProductDetails { get; set; }

		public CatalogItemModel CatalogItem { get; set; }

		public List<ProductDetailsModel> Products { get; set; }
	}
}

Store/Store/Controllers/CatalogController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Store.Domen.Interfaces.Services;
using Store.Interfaces;
using Store.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Store.Controllers
{
	public partial class CatalogController : ControllerBase
	{
		private readonly ICatalogModelBuilder _catalogModelBuilder;
		private readonly ICatalogService _catalogService;
		private readonly IProductService _productService;
		private readonly IMapper _mapper;

		public CatalogController(
			ICatalogModelBuilder catalogModelBuilder,
			ICatalogService catalogService,
			IProductService productService,
			IMapper mapper)
		{
			_catalogModelBuilder = catalogModelBuilder;
			_catalogService = catalogService;
			_productService = productService;
			_mapper = mapper;
		}

		// GET: CatalogController
		public ActionResult Index()
		{
			return RedirectToAction(nameof(Details), new { id = 0});
		}

		// GET: CatalogController/Details/5
		public async Task<ActionResult> Details(int id)
		{
			var currentCategory = (await _catalogService.GetAsync(c => c.Id == id)).FirstOrDefault();
			var pageTitle = currentCategory != null ? currentCategory.Name : ControllerName;

			_catalogModelBuilder.Init(pageTitle);

			var categories = (await _catalogService.GetAsync(c => c.ParentId == id))
				.Select(c => _mapper.Map<CatalogItemModel>(c));

			_catalogModelBuilder.SetCategories(categories);

			var products = (await _productService.GetAsync(p => p.CategoryId == id))
				.Select(p => _mapper.Map<ProductDetailsModel>(p));
			
			_catalogModelBuilder.SetProducts(products);

			return View("Index", _catalogModelBuilder.Build());
		}
	}
}

Store/Store/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Store.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Store.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Store/Store/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Store.Domen.Interfaces.Services;
using Store.Interfaces;
using Store.Models;
using System.Linq;
using System.Threading.Tasks;

namespace Store.Controllers
{
	public partial class ProductController : ControllerBase
	{
		private readonly IProductModelBuilder _productModelBuilder;
		private readonly ICatalogModelBuilder _catalogModelBuilder;
		private readonly ICatalogService _catalogService;
		private readonly IProductService _productService;
		private readonly IMapper _mapper;

		public ProductController(
			IProductModelBuilder productModelBuilder,
			ICatalogModelBuilder catalogModelBuilder,
			ICatalogService catalogService,
			IProductService productService,
			IMapper mapper)
		{
			_productModelBuilder = productModelBuilder;
			_catalogModelBuilder = catalogModelBuilder;
			_catalogService = catalogService;
			_productService = productService;
			_mapper = mapper;
		}

		// GET: ProductController
		public async Task<ActionResult> Index()
		{
			_catalogModelBuilder.Init(ControllerName);

			var products = (await _productService.GetAsync())
					.Select(p => _mapper.Map<ProductDetailsModel>(p));

			_catalogModelBuilder.SetProducts(products);
			
			return View("~/Views/Catalog/Index.cshtml", _catalogModelBuilder.Build());
		}

		// GET: ProductController/Details/5
		public async Task<ActionResult> Details(int id)
		{
			var product = (await _productService.GetAsync(p => p.Id == id)).FirstOrDefault();
			if (product == null)
			{
				return NotFound(id);
			}

			var productDetails = _mapper.Map<ProductDetailsModel>(product);
			_productModelBuilder.Init(productDetails.Title);

			_productModelBuilder.SetProductDetails(productDetails);

			var category = (await _catalogService.GetAsync(c => c.Id == product.CategoryId)).FirstOrDefault();
			_productModelBuilder.SetCatalogItem(_mapper.Map<CatalogItemModel>(category));

			var products = (await _productService.GetAsync(p => p.CategoryId == productDetails.CategoryId))
				.Select(p => _mapper.Map<ProductDetailsModel>(p));

			_productModelBuilder.SetProducts(products);

			return View(_productModelBuilder.Build());
		}
	}
}

Store/Store/Views/Catalog/Index.cshtml
@model CatalogModel
@{
	ViewData["Title"] = ViewData["Title"] ?? Model.Title;
	var isAdmin = false;
}
<div>Breadcrumbs</div>
<hr />
<div class="container">
	<div class="row">
		<div class="col-3">
			<div>
				@if (Model.Categories.Count > 0)
				{
					<h3>Category</h3>
					<hr />
					<ul class="nav flex-column">
						@foreach (var category in Model.Categories)
						{
							<li class="nav-item">@Html.ActionLink(category.Title, "Details", "Catalog", new { id = category.Id }, null)</li>
						}
					</ul>
				}
			</div>
			<div>
				@if (Model.Products.Count > 0)
				{
					<h3>Filter by</h3>
					<hr />
					<p>filters...</p>
				}
			</div>
		</div>
		<div class="col-9">
			<h3>@Model.Title</h3>
			<hr />
			@if (Model.Categories.Count > 0)
			{
				<div class="container">
					<div class="card-columns">
						@foreach (var category in Model.Categories)
						{
							<div class="card">
								<div class="card-body">
									<h5 class="card-title">@Html.ActionLink(category.Title, "Details", "Catalog", new { id = category.Id }, null)</h5>
									<p class="card-text">@category.Description</p>

								</div>
								<div class="card-footer">
									<ul class="nav flex-column">
										@if (isAdmin)
										{
											<li class="nav-item">@Html.ActionLink("Edit", "Edit", "Catalog", new { id = category.Id }, null)</li>
											<li class="nav-item">@Html.ActionLink("Delete", "Delete", "Catalog", new { id = category.Id }, null)</li>
										}
									</ul>
								</div>
							</div>
						}
					</div>
				</div>
				<hr />
			}
			@if (Model.Products.Count > 0)
			{
				<div class="container">
					<div class="card-columns">
						@foreach (var product in Model.Products)
						{
							<div class="card">
								<div class="card-body">
									<h5 class="card-title">@Html.ActionLink(product.Title, "Details", "Product", new { id = product.Id }, null)</h5>
									<p class="card-text">@product.Description</p>

								</div>
								<div class="card-footer">
									<ul class="nav flex-column">
										@if (isAdmin)
										{
											<li class="nav-item">@Html.ActionLink("Edit", "Edit", "Product", new { id = product.Id }, null)</li>
											<li class="nav-item">@Html.ActionLink("Delete", "Delete", "Product", new { id = product.Id }, null)</li>
										}
									</ul>
								</div>
							</div>
						}
					</div>
				</div>
			}
		</div>
	</div>
</div>

Store/Store/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Store/Store/Views/Product/Details.cshtml
@model ProductModel
@{
	ViewData["Title"] = ViewData["Title"] ?? Model.Title;
	var isAdmin = false;
}
<div>Breadcrumbs</div>
<hr />
<div class="container">
	<div class="row">
		<div class="col-3">
			<div>
				@if (Model.Products.Count > 0)
				{
					<h3>@Model.CatalogItem.Title</h3>
					<hr />
					<ul class="nav flex-column">
						@foreach (var product in Model.Products)
						{
							<li class="nav-item">@Html.ActionLink(product.Title, "Details", "Product", new { id = product.Id }, null)</li>
						}
					</ul>
				}
			</div>
		</div>
		<div class="col-9">
			<div class="card m-3" style="max-width: 640px;">
				<div class="row g-0">
					<div class="col-md-4">
						<img src="https://mdbcdn.b-cdn.net/wp-content/uploads/2020/06/vertical.webp"
							 alt="Trendy Pants and Shoes"
							 class="img-fluid rounded-start" />
					</div>
					<div class="col-md-8">
						<div class="card-body">
							<h5 class="card-title">@Model.Title</h5>
							<p class="card-text">@Model.ProductDetails.Description</p>
							<p class="card-text">
								<small class="text-muted">Last updated 3 mins ago</small>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

Store/Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Health Store</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Index">Catalog</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
						</li>
					</ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Store - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>